version: '3.8'

services:
  app:
    build: 
        context: ./
        dockerfile: dockerfiles/app/Dockerfile
    ports:
        - "22107:3000"
    volumes:
        - .:/app
    depends_on:
        - db
  db:
    build:
        context: ./
        dockerfile: dockerfiles/mysql/Dockerfile
    environment: 
        MYSQL_DATABASE: blog_db
        MYSQL_USER: blog_user
        MYSQL_PASSWORD: blog_pass44
        MYSQL_ROOT_PASSWORD: root_pass44
    ports:
        - "3383:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql